remove default threshold for sensititvity
gridsuite/sensitivity-analysis-server pull request #28
Opened 2023-07-28 12:16 UTC by Walid-Sahnoun

2023-07-31 11:37 UTC, FranckLecuyer requested changes
remove also 'resultsThreshold' field in SensitivityAnalysisInputData.java, 
and comment in SensitivityAnalysisWorkerService.java

2023-07-31 11:37 UTC, FranckLecuyer commented on src/main/resources/config/application.yaml
> -  results-threshold: 0.01
The same removal must also be made in deployment : k8s/resources/study/config/sensitivity-analysis-server-application.yml file

2023-08-02 09:10 UTC, FranckLecuyer requested changes
There are still references to resultsThreshold ...

2023-08-10 08:14 UTC, FranckLecuyer approved these changes

2023-08-10 08:55 UTC, AAJELLAL approved these changes

2023-08-10 09:20 UTC, merged