Use one transaction for inserting status and results.
gridsuite/sensitivity-analysis-server pull request #35
Opened 2023-09-20 12:45 UTC by antoinebhs

2023-09-21 11:23 UTC, FranckLecuyer requested changes

2023-09-21 11:23 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/sensitivityanalysis/server/repositories/SensitivityAnalysisResultRepository.java
> +            globalStatusRepository.save(toStatusEntity(resultUuid, status));
status should be saved even if result is null

2023-09-21 13:17 UTC, FranckLecuyer approved these changes

2023-09-28 15:09 UTC, SlimaneAmar approved these changes

2023-09-28 15:32 UTC, merged