Add an api to retrieve filter options in sensi results
gridsuite/sensitivity-analysis-server pull request #36
Opened 2023-09-22 15:06 UTC by YenguiSeddik

2023-09-26 16:32 UTC, etiennehomer requested changes

2023-09-26 16:32 UTC, etiennehomer commented on src/main/java/org/gridsuite/sensitivityanalysis/server/repositories/SensitivityAnalysisResultRepository.java
> +        SensitivityResultFilterOptions.SensitivityResultFilterOptionsBuilder sensitivityResultOptionsBuilder = SensitivityResultFilterOptions.builder()
You could do : 
SensitivityResultFilterOptions.SensitivityResultFilterOptionsBuilder sensitivityResultOptionsBuilder = SensitivityResultFilterOptions.builder()
                .allFunctionIds(sensitivityRepository.findFunctionByResultResultUuidAndFactorFunctionType(sas.getResultUuid(), selector.getFunctionType()))
                .allVariableIds(sensitivityRepository.findVariableByResultResultUuidAndFactorFunctionType(sas.getResultUuid(), selector.getFunctionType()));
        if (selector.getIsJustBefore()) {
            sensitivityResultOptionsBuilder.allContingencyIds(sensitivityRepository.findContingencyByResultResultUuidAndFactorFunctionType(sas.getResultUuid(), selector.getFunctionType())
                    .stream()
                    .filter(Objects::nonNull)
                    .collect(Collectors.toList()));
        }
        return sensitivityResultOptionsBuilder.build();

2023-09-27 16:33 UTC, etiennehomer commented on src/main/java/org/gridsuite/sensitivityanalysis/server/repositories/SensitivityAnalysisResultRepository.java
> +                    .build();
remove the build()

2023-09-27 16:46 UTC, etiennehomer approved these changes

2023-09-28 10:04 UTC, FranckLecuyer approved these changes

2023-09-28 14:21 UTC, merged