Refactor result selector
gridsuite/sensitivity-analysis-server pull request #42
Opened 2023-10-06 15:17 UTC by YenguiSeddik

2023-10-11 15:30 UTC, anistouri requested changes
You can change the attribute isJustBefore in SensitivityRunQueryResult

2023-10-12 15:32 UTC, Meklo approved these changes
Code: OK, just clean up isJustBefore as mentionned by @anistouri 
Tests: OK

2023-10-17 12:48 UTC, anistouri approved these changes

2023-10-19 10:04 UTC, ayolab approved these changes

2023-10-25 07:32 UTC, merged