Add provider to parameters
gridsuite/sensitivity-analysis-server pull request #66
Opened 2024-02-13 15:40 UTC by ayolab

2024-02-14 14:15 UTC, dbraquart requested changes
code: things to change with provider managment in runContext

test: an issue when we have specific LF param (du to null provider) 
-> Sensitivity analysis provider not found null

2024-02-14 14:15 UTC, dbraquart commented on src/main/java/org/gridsuite/sensitivityanalysis/server/service/SensitivityAnalysisService.java
>          SensitivityAnalysisRunContext runContext = new SensitivityAnalysisRunContext(networkUuid, variantId, inputData, receiver, provider, reportInfos, userId);
you cannot use 'provider' here, it is nnot sent by the Front.
Like in SA, SensitivityAnalysisRunContext has to read entity to get the provider (and maybe use default provider if missing)

2024-02-14 14:15 UTC, dbraquart commented on src/main/java/org/gridsuite/sensitivityanalysis/server/SensitivityAnalysisController.java
>                                             @Parameter(description = "reporterId") @RequestParam(name = "reporterId", required = false) String reporterId,
Line 98 you have to remove provider param (not sent by the Front)

2024-02-14 15:49 UTC, dbraquart approved these changes
code: ok
tests: ok

2024-02-22 16:51 UTC, SlimaneAmar approved these changes

2024-02-23 14:22 UTC, merged