Add a reporter Id
gridsuite/sensitivity-analysis-server pull request #7
Opened 2022-10-12 13:48 UTC by SlimaneAmar

2022-10-18 09:39 UTC, laurgarn approved these changes

2022-10-19 14:45 UTC, FranckLecuyer requested changes

2022-10-19 14:49 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/sensitivityanalysis/server/service/SensitivityAnalysisWorkerService.java
> +        if (context.getReportUuid() != null) {
Done

2022-10-20 08:20 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/sensitivityanalysis/server/service/SensitivityAnalysisWorkerService.java
> +            reporter = rootReporter.createSubReporter(SENSI_TYPE_REPORT, SENSI_TYPE_REPORT + " (${providerToUse})", "providerToUse", context.getProvider());
Done

2022-10-20 13:58 UTC, FranckLecuyer approved these changes

2022-10-21 12:41 UTC, merged